game:
  use_ui: False
  row_count: 16
  col_count: 16
  cell_size: 20
  food_count: 80
  interval: 0.03
ml:
  player:
    fake: False
    max_steps: 50
  grid_view:
    reciprocate_distances: False
    food_squarewise: True
    food_diagonal: False
    death_squarewise: True
    death_diagonal: False
  brain:
    layer_sizes: "4, 4" # CSV string
  generation:
    population: 6
  evolution:
    selection_ratio: 0.4
