game:
  row_count: 6
  col_count: 6
  cell_size: 20
  interval: 0.03
  snake:
    max_steps: 50
ml:
  evolution:
    selection_ratio: 0.5
    generations: 2
  generation:
    population: 2
  player:
    tbc: "tbc"
  brain:
    layer_sizes: "4, 4" # CSV string
    save_dir: "./models/"
  grid_view:
    reciprocate_distances: False
    food_squarewise: True
    food_diagonal: False
    death_squarewise: True
    death_diagonal: False
