game:
  use_ui: False
  row_count: 8
  col_count: 8
  cell_size: 20
  interval: 0.03
  snake:
    max_steps: 200
ml:
  evolution:
    selection_ratio: 0.2
    generations: 2
  generation:
    population: 8
  player:
    tbc: "tbc"
  brain:
    layer_sizes: "4, 4" # CSV string
    save_dir: "./models/"
  grid_view:
    reciprocate_distances: False
    food_squarewise: True
    food_diagonal: False
    death_squarewise: True
    death_diagonal: False
